### ISSUE TITLE
Couple of quick little issues, collecting them here so I don't lose them

### ISSUE THREAD

**Issue by johnnymugs** [Context-Travel/dotfiles#3]
- I would expect Vundle to have been installed as a submodule on the initial cloning but it's not -- might be user error on my part
- On OSX the tmate.conf file that rebinds the prefix key causes us to be unable to use the prefix key within tmux. Removing the tmate.conf file fixes it for us, but maybe this is necessary in linux?
- installed tmuxp but couldn't get it running on either of our OSX machines, will need to investigate
- we should add a shared git config

**Comment by rmeritz** [comment]
These issues have either been fixed or are in tracker tickets so I'm closing this.
